server:
  port: 8082

spring:
  application:
    name: FRAUD
  zipkin:
    base-url: http://localhost:9411

  datasource:
    url: jdbc:postgresql://localhost:5432/fraud
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
